# stcp 转发示例 - 被连接端
# https://gofrp.org/zh-cn/docs/examples/stcp/
serverAddr = ""
serverPort = 7000
dnsServer = "114.114.114.114"
loginFailExit = false

[log]
level = "debug"
disablePrintColor = true

[[proxies]]
name = "secret_ssh"
type = "stcp"
# 只有与此处设置的 secretKey 一致的用户才能访问此服务
secretKey = "abcdefg"
localIP = "127.0.0.1"
localPort = 22